### ISSUE TITLE
Add HACS support för easy upgrade

### ISSUE THREAD

**Issue by fredamn76** [zsarnett/Custom-Grid-View#10]

**Comment by jjlink** [comment]
Why does HACS say this when I try to add https://github.com/zsarnett/Custom-Grid-View as a custom repository?
"Repostitory structure for 0.0.3 is not compliant"

**Comment by Xlinx64** [comment]
@jjlink It will be available with the next release.

**Comment by K-RAD** [comment]
I'm getting `Repostitory structure for 0.0.3 is not compliant` when trying to add it to HACS

**Comment by zsarnett** [comment]
I am going to try and get the release out today. I want to put more in it but I'll at least get the HACS version out today

**Comment by nofuturekid** [comment]
Still getting "not compliant" for v0.0.4

**Comment by Xlinx64** [comment]
Hey @nofuturekid!
It works for me. Did you select **lovelace** in the category field?

**Comment by nofuturekid** [comment]
Was missing the obvious ;). With "lovelace" selected indeed it works.
