### ISSUE TITLE
View blacks out when adding cards. 003 FIXES THIS

### ISSUE THREAD

**Issue by msauto** [zsarnett/Custom-Grid-View#6]

**Comment by msauto** [comment]
I was able to get the alarm card that was added back by deleting the "-null" entry but it seems to have completely deleted the entity card that i edited pryor. The yaml for that card is even gone
![Screenshot (88)](https://user-images.githubusercontent.com/42117859/102158158-6c449980-3e46-11eb-9177-fb5679c443e2.png)
 from the raw editor.

**Comment by jjlink** [comment]
Do we need to download a new version of the js file to test the changes?

I'm seeing the same sort of problems:

views:
  - path: default_view
    type: 'custom:grid-dnd'
    title: Home
    cards:
      - null
      - null
      - null
      - null
      - null
      - type: button
        tap_action:
          action: toggle
        entity: switch.002008635ccf7f50aed1
        layout:
          key: 1323588a-de52-4025-ab9c-543bf7db4ecc
      - type: entities
        entities:
          - binary_sensor.wyzesense_77a67a2e
  - path: ecobee

**Comment by msauto** [comment]
I downloaded the new version with no joy. But yes i would assume you would need to download and place inside your www folder.

**Comment by msauto** [comment]
I apoligize!! I can confirm 003 fixes this issue ! Just download new file [Here](https://github.com/zsarnett/Custom-Grid-View/releases)
Then place inside your www folder and RESTART HOME ASSISTANT , lol (I forgot to do the last part)

**Comment by jjlink** [comment]
I'm still seeing the issue after downloading the new grid-view.js file and replacing it in the www folder, restarting HA. 
Is there anything else that needs to be done?
Thanks

**Comment by jjlink** [comment]
Interesting I just tried with a different browser (Edge) and it worked fine. Its not working in the Brave browser. Could this be a caching problem?

**Comment by zsarnett** [comment]
Definitely could be caching
